### ISSUE TITLE
panic due to unrecognised data type

### ISSUE THREAD

**Issue by Sekenre** [kyai/redis-cui#1]
Redis version 5.0.5

I was just trying this project out for the first time with my local test redis instance and I got this error while browsing through my keys.

I only have one streaming key and didn't need to browse it, would it be possible to fix it so that unknown datatypes are simply skipped over?

```
panic: Unknown type: STREAM

goroutine 1 [running]:
log.Panic(0xc0000a99a8, 0x2, 0x2)
        /usr/lib/go/src/log/log.go:333 +0xac
github.com/kyai/redis-cui/class.NewClass(0xc000318c46, 0x6, 0xc00014c000, 0x6, 0xc0000a9bd0)
        /home/kio/go/src/github.com/kyai/redis-cui/class/class.go:34 +0x191
github.com/kyai/redis-cui/cui.renderData(0xc0001640f0, 0x0)
        /home/kio/go/src/github.com/kyai/redis-cui/cui/render.go:103 +0x8d0
github.com/kyai/redis-cui/cui.handleKeysSelect(0xc00014c000, 0xc0001640f0, 0x0, 0x0, 0x5)
        /home/kio/go/src/github.com/kyai/redis-cui/cui/event.go:102 +0x54
github.com/kyai/redis-cui/cui.handleKeysNextLine(0xc00014c000, 0xc0001640f0, 0x4, 0xc0000a9d01)
        /home/kio/go/src/github.com/kyai/redis-cui/cui/event.go:89 +0x3a
github.com/kyai/gocui.(*Gui).execKeybindings(0xc00014c000, 0xc0001640f0, 0xc0000a7dc0, 0x0, 0x6, 0x7)
        /home/kio/go/src/github.com/kyai/gocui/gui.go:647 +0xc4
github.com/kyai/gocui.(*Gui).onKey(0xc00014c000, 0xc0000a7dc0, 0x2, 0x0)
        /home/kio/go/src/github.com/kyai/gocui/gui.go:611 +0x1b3
github.com/kyai/gocui.(*Gui).handleEvent(...)
        /home/kio/go/src/github.com/kyai/gocui/gui.go:426
github.com/kyai/gocui.(*Gui).MainLoop(0xc00014c000, 0x0, 0x1)
        /home/kio/go/src/github.com/kyai/gocui/gui.go:386 +0x1e3
github.com/kyai/redis-cui/cui.New()
        /home/kio/go/src/github.com/kyai/redis-cui/cui/cui.go:60 +0x22a
main.main()
        /home/kio/go/src/github.com/kyai/redis-cui/main.go:23 +0x22f
```

**Comment by kyai** [comment]
Fixed this error, and added support for STREAM datatypes.

**Comment by Sekenre** [comment]
Amazing, thanks so much!
